version: '3'

services:
  trip-app:
    image: "willylui/trip-app-sever:latest"
    build:
      dockerfile: ./Dockerfile
    ports:
      - '3000:3000'
  postgres:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: trip_app
    ports:
      - '5432:5432'
    volumes:
      - ./pgdata:/var/lib/postgresql/data
